### PR TITLE
Add https support for private docker registries and support Basic realm

### PR DESCRIPTION
**Pull request by logingood**
Hi, 

I've managed to add Basic Realm authentication and `https` support for private Docker registries. Certain values were hardcoded and bound to the Docker hub, which is not usable in case the registry is private.

I would appreciate if it is possible to merge these changes and ready to make all necessary adjustments. Currently we are using forked branch to support private registry. 

Sorry no tests so far :/

Thanks

### CODE REVIEW

**Comment by murat1985** [comment]
Hi, 

@jgsqware sorry for mentioning you but is it possible to take a look at this PR ? I have submitted it a while ago and no one returned back since that time. We decided to use this tool together with Clair and it would be great to get this changes back to upstream as they seem useful. 

Thank you in advance.

**Comment by jgsqware** [comment]
sorry for the big delay, I will have a look this week. thank you for the
interest and PR however

**Comment by jdel** [comment]
@murat1985: Hello Murat, I have built your fork of hyperclair and it works great with my private repo using https. However, your fork breaks pulling from the original repo: 

```
# hyperclair --log-level debug pull frolvlad/alpine-glibc
DEBU[0000] Using config file: /root/hyperclair.yml
INFO[0000] pulling image: https://frolvlad/v2/alpine-glibc:latest
service is unavailable
```

**Comment by murat1985** [comment]
Hi @jdel thank you for heads-up, will fix it very soon (today or over the weekend).

**Comment by murat1985** [comment]
@jdel you probably tried the master branch, I made these fixes already in cleanup branch (I created this PR against cleanup branch). I have rebased it, please try once again. Thank you, very much for testing.

**Comment by murat1985** [comment]
ah you are right, sorry, messed with my go path. Fix is coming.

**Comment by murat1985** [comment]
yes I double checked, that was fixed in this branch and it is fixed in my fork as well:
```
go get github.com/murat1985/hyperclair
```
and then
```
$GOBIN/hyperclair   --log-level debug pull frolvlad/alpine-glibc
DEBU[0000] Using config file: /root/hyperclair.yml
INFO[0000] pulling image: https://registry-1.docker.io/v2/frolvlad/alpine-glibc:latest
```

sorry for previous confusion, I had old sources in my $GOPATH/src

**Comment by jdel** [comment]
Thanks, i will recompile and give it a go.

**Comment by jdel** [comment]
@murat1985 I have recompiled your fork's master branch, and now it throws an error about not being logged in:

```bash
# hyperclair.linux.amd64 --log-level debug pull frolvlad/alpine-glibc
DEBU[0000] Using config file: /root/hyperclair.yml
INFO[0000] pulling image: https://registry-1.docker.io/v2/frolvlad/alpine-glibc:latest
INFO[0000] Pull is Unauthorized
service is unavailable
FATA[0000] pulling image frolvlad/alpine-glibc: authenticating: user is not log in
sf-clair bin # hyperclair.linux.amd64 login
Username: jdel
Password:
Login Successful
# hyperclair.linux.amd64 --log-level debug pull frolvlad/alpine-glibc
DEBU[0000] Using config file: /root/hyperclair.yml
INFO[0000] pulling image: https://registry-1.docker.io/v2/frolvlad/alpine-glibc:latest
INFO[0000] Pull is Unauthorized
service is unavailable
FATA[0000] pulling image frolvlad/alpine-glibc: authenticating: user is not log in
```

**Comment by murat1985** [comment]
Hi @jdel, genuinely sorry for this mess. It should be fine now. I messed with the url that was used to retrieve login details from configuration file. As I have introduced http/https distinction, I'd like to have schema in the URLs that are stored in configuration file `~/.hyperclair/config.json`. Now it should work fine. 

I really appreciate your help with this PR. Thank you!

```
hyperclair  --log-level debug pull frolvlad/alpine-glibc
DEBU[0000] Using config file: /root/hyperclair.yml
INFO[0000] pulling image: https://registry-1.docker.io/v2/frolvlad/alpine-glibc:latest
INFO[0001] Pull is Unauthorized

Image: https://registry-1.docker.io/v2/frolvlad/alpine-glibc:latest
 3 layers found
  ➜ sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
  ➜ sha256:cb547f391fe0516d64dfe2199c9fd4bf672b5ee5026ac9db852b945f8e3a9837
  ➜ sha256:3690ec4760f95690944da86dc4496148a63d85c9e3100669a318110092f6862f
```

**Comment by jgsqware** [comment]
hi there! I will investigate your PR and merge it to the repo
jgsqware/clairctl.
Hyperclair will be deprecated soon and replaced by clairctl.

thanks for the effort, I really appreciate it.

**Comment by murat1985** [comment]
Thanks @jgsqware

**Comment by murat1985** [comment]
I can recreate PR against new repository if it helps

**Comment by jgsqware** [comment]
@murat1985 you shoud try the PR https://github.com/jgsqware/clairctl/pull/10

i've fixed clairctl pull with insecure registry (with a - - insecure)  and I use the docker lib for authentication so probably the basic realm auth will work

**Comment by jgsqware** [comment]
let comment on the other PR if it the same purpose as this one

**Pull request closed without merging**
